POST http://localhost:8080/api/rating
Content-Type: application/json

{
  "game": "jigsaw",
  "rated_on": "2021-05-06T01:30:00",
  "username": "Adam",
  "rating": 2
}

###

POST http://localhost:8080/api/rating
Content-Type: application/json

{
  "game": "jigsaw",
  "rated_on": "2021-01-03T00:30:00",
  "username": "Karol",
  "rating": 5
}

###


POST http://localhost:8080/api/rating
Content-Type: application/json

{
  "game": "jigsaw",
  "rated_on": "2021-05-09 22:47:03.099000",
  "username": "Peter",
  "rating": 2
}

###



POST http://localhost:8080/api/rating
Content-Type: application/json

{
  "game": "jigsaw",
  "rated_on": "2021-05-09 22:47:03.099000",
  "username": "Jozef",
  "rating": 3
}

###


